version: '3.9'

services:
  build:
    image: scrcpy-docker:latest
    build:
      context: ./build

  mirror:
    build:
      context: .
      args:
        - USER=$USER
        - GROUP=$USER
    environment:
      - DISPLAY=$DISPLAY
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - ADDRESS=192.168.11.62
      - SCRCPY_ARGS=--max-size=480 --max-fps=1 --video-bit-rate=512K --audio-bit-rate=8K --audio-buffer=500 --window-height=720
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/snd:/dev/snd
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
      - ./cache:/home/$USER/cache
      - ./.android:/home/$USER/.android
    tty: true
    stdin_open: true
    privileged: true
